diamonds
========================================================

### loading libraries and some basic diamonds dataset information

setwd('~/Documents/DataScience/R/UdacityR/')

library(ggplot2)
library(GGally)
library(scales)
library(memisc)
library(lattice)
library(MASS)
library(car)
library(reshape2)
library(dplyr)
library(gridExtra)

# sessionInfo()

data("diamonds")

# View(diamonds)

dim(diamonds)
# 10 columns and over 50K rows

?diamonds

str(diamonds)

summary(diamonds)

# cut: 5 levels (Fair, Good, Very Good, Premium, Ideal)
# color: 7 levels (diamond colour, from J (worst) to D (best))
# clarity: 8 levels (a measurement of how clear the diamond is (I1 (worst), SI1, SI2, VS1, VS2, VVS1, VVS2, IF (best)))
# price: in US dollars
# x, y, z: in mm

head(sort(table(diamonds$carat), decreasing = T))
# top 6: less or equal to 1 carat
head(sort(table(diamonds$carat), decreasing = T), 10)
# top 10: the same as above. Less or equal to 1 carat


head(sort(table(diamonds$price), decreasing = T))
head(sort(table(diamonds$price), decreasing = T), 10)
# top 10: less than 1000

### Histogram and Scatterplot Review

ggplot(aes(x=price), data=diamonds)+geom_histogram(bins=50)+scale_x_log10()+ggtitle('Price with log10 Scale')
# bimodel distribution
# common distribution pattern: poor and rich groups

ggplot(aes(x=carat,y=price),data=diamonds)+scale_x_continuous(lim=c(0.2,quantile(diamonds$carat,0.99)))+scale_y_sqrt(lim=c(200,quantile(diamonds$price,0.99)))+geom_jitter(alpha=0.1)+stat_smooth(method='lm')
# carat Vs price plot

ggplot(aes(x=carat,y=price,color=clarity),data=diamonds)+scale_x_continuous(lim=c(0.2,quantile(diamonds$carat,0.99)))+scale_y_sqrt(lim=c(200,quantile(diamonds$price,0.99)))+geom_jitter(alpha=0.1)+stat_smooth(method='lm')
# similar plots as the above one. Added clarity into the plot

### ggpairs with 5000 random selected samples

set.seed(5000)

diamond_samp <- diamonds[sample(1:length(diamonds$price), 5000), ]
# sample 5,000 diamonds from the data set

ggpairs(diamond_samp)
ggsave('ggpairs_diamond.png',width=12, height= 12)
# price depend on carat, x, y, z

### Size matters

# Besides carat, are there other ways/measurement to get an idea about the size of a diamond?
diamonds$xyz<-(diamonds$x*diamonds$y*diamonds$z)^(1/3)
# adding a new column to the dataframe

ggplot(aes(x=xyz, y=price), data = diamonds) + geom_point() + scale_y_log10()
# outliers at the left side of the plot are due to the fact that there are 0 in x, y, z

ggplot(aes(x=xyz, y=price), data = diamonds) + scale_x_continuous(lim=c(3,quantile(diamonds$xyz,0.99)))+ geom_point(alpha=0.1) + scale_y_log10(lim=c(500,quantile(diamonds$price,0.99)))+ ggtitle('Price (log10) by Cube-Root of xyz(size)')
# over-plotting
# changing alpha value does not help to solve this issue


### Cut, Clarity and Color Variable
ggplot(aes(x=xyz, y=price, color=cut), data = diamonds) + scale_x_continuous(lim=c(3,quantile(diamonds$xyz,0.99)))+ geom_point(alpha=0.1) + scale_y_log10(lim=c(500,quantile(diamonds$price,0.99)))+ ggtitle('Price (log10) by Cube-Root of xyz(size)') + scale_color_brewer(type = 'div', guide = guide_legend(title = 'cut', reverse = T, override.aes = list(alpha = 1, size = 2)))
table(diamonds$cut)
# very hard to see if there is any pattern
# most of the diamonds are Ideal, Premium or Very Good
    
ggplot(aes(x=xyz, y=price, color=clarity), data = diamonds) + scale_x_continuous(lim=c(3,quantile(diamonds$xyz,0.99)))+ geom_point() + scale_y_log10(lim=c(500,quantile(diamonds$price,0.99)))+ ggtitle('Price (log10) by Cube-Root of xyz(size)') + scale_color_brewer(palette = "Greens", type = 'div', guide = guide_legend(title = 'clarity', reverse = T, override.aes = list(alpha = 1, size = 2)))
# Under similar conditions, better clarity tends to go higher in price
    
ggplot(aes(x=xyz, y=price, color=color), data = diamonds) + scale_x_continuous(lim=c(3,quantile(diamonds$xyz,0.99)))+ geom_point() + scale_y_log10(lim=c(500,quantile(diamonds$price,0.99)))+ ggtitle('Price (log10) by Cube-Root of xyz(size)') + scale_color_brewer(palette = "Blues", type = 'div', guide = guide_legend(title = 'color',  override.aes = list(alpha = 1, size = 2)))
# Under similar conditions, better color tends to go higher in price


### Building Linear Model with lm()

fit1 <- lm(log(price) ~ xyz, data = diamonds)
fit2 <- update(fit1, ~ . + color)
fit3 <- update(fit2, ~ . + clarity)
mtable(fit1, fit2, fit3)